### ISSUE TITLE
[Ускорение] использовать API метод execute 

### ISSUE THREAD

**Issue by Tegoruk** [zpix1/vkpmdownloader#1]
Привет! Спасибо за отличную программу.
Для ускорения можно использовать vk.com/dev/execute. Как я вижу, ты пользуешься библиотекой `vk` , в ней нет встроенной поддержки execute.
В https://github.com/python273/vk_api есть, рекомендую попробовать

с execute можно добиться большого ускорения программы

**Comment by zpix1** [comment]
Привет,
execute не сильно поможет, у него тоже есть ограничение размера возвращаемого массива (до 200 сообщений, диалогов и тп), основную часть времени работы программы и занимает обход этого барьера - последовательная загрузка по 200 элементов.
`vk` - не более чем обертка для обычного http api vk, думаю в ней можно найти сессию и вызвать `execute` напрямую, или самому дописать такой метод.
Спасибо за интерес к программе
